### ISSUE TITLE
[Question/Feedback]: Monitor Disable Parameter

### ISSUE THREAD

**Issue by MohmadEh** [Azure/azure-monitor-baseline-alerts#131]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

In some VM JSON policies, the Monitor Disable Parameter is not available

**Comment by Brunoga-MS** [comment]
Hello @MohmadEh ,
thanks for your feedback. I will take a look at the files and let you know as soon as possible.

Thanks,
Bruno.

**Comment by Brunoga-MS** [comment]
Hello @MohmadEh,
as promised I investigated and found out that these alerts are on a subscription scope, so that tag will not really apply as we imagine. Moreover, tagging a subscription with the _**MonitorDisable**_ will stop all the alerts on all resources. Should you need to exclude VMs, you could change the query by adding a **_where_** condition, right after the table name, to exclude computers with given names or in a given list. It could be something like:

```
Heartbeat
| where Computer !in ('ServerA', 'ServerB', 'ServerC')
```

Thanks,
Bruno.
