### ISSUE TITLE
Can AMBA respect existing single user defined Managed Identity 

### ISSUE THREAD

**Issue by stevedistef** [Azure/azure-monitor-baseline-alerts#175]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Deployment of AMBA Policies includes what seem to be system assigned managed identities for each of the ALZ areas as shown here (my deployment is AMBA Unaligned so you see them all in one place under the MG with that same name):
![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/159309739/cf4c9129-aff8-4119-8e0f-269c121c9756)

So thats 6 MIs that are Contributors in existing customer management group. 
The customer has security policy to instead use their own, single User Defined Managed Identity for all Policy contributor roles.

Customer modified to use their own after deployment and was working fine, but now every subsequent deployment clobbers over their MI and requires clean up again (not acceptable). 

![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/159309739/92840e28-8a1e-4999-96cd-4c490b7683b5)

Is there not a way we can parameterize this value in the parameters template and have it use the customers user defined MI instead?

**Comment by Brunoga-MS** [comment]
Hello @stevedistef ,
thanks for your feedback. At the moment this is not a scenario we have in our plans. There are several things to be considered when offering this option. For instance, the assignment scope will be per subscription instead of per MG like in the case of  System Assigned. As a workaround the customer can either change the identity in the assignment manually or change it in the code for policy assignments (under the **_policyAssignments_** folder) so every time AMBA gets re-deployed it will be using the UAMI.

Hope that helps.

Thanks,
Bruno.
