### ISSUE TITLE
[Question/Feedback]: Will AMBA be updated to support the transition from Log Analytics to Azure Monitor agents including DCRs?

### ISSUE THREAD

**Issue by ThojoUno** [Azure/azure-monitor-baseline-alerts#186]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

What is the roadmap for AMBA with the pending deprecation of Log Analytics agents?

**Comment by Brunoga-MS** [comment]
Hello @ThojoUno,
Thanks for your feedback. AMBA, as far as I know, is not be impacted by that because we do not deploy any monitoring agent (neither Log Analytics agent, nor AMA). We just rely on metrics (which are agentless) and collected logs for virtual machine alerts (see [Log Alert](https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/Monitoring-and-Alerting/#log-alerts) where we do refer to VMInsights deployment guidance). That said, we don't have this item in our roadmap as we don't install it via AMBA. Customers will migrate to AMA prior to the deprecation date (August 31, 2024) as part of their journey beyond AMBA which will just continue to work normally as long as the collection will happen.

Hope that helps.

Thanks,
Bruno.

**Comment by Brunoga-MS** [comment]
Hello @ThojoUno ,
I am going to close this issue as resolved. Feel free to reopen it or to create a new one should it be the case.

Thanks,
Bruno.
