### ISSUE TITLE
[Question]: is a non-default windowSize properly enforced in KQL queries?

### ISSUE THREAD

**Issue by powershellpr0mpt** [Azure/azure-monitor-baseline-alerts#262]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

I have a question concerning the **windowSize** value of an alert:

We have configured one of the alerts, the [VMOSDiskReadLatencyAlert ](https://github.com/Azure/azure-monitor-baseline-alerts/blob/7e113576f619293ce2be10065981b6f604aeac06/patterns/alz/alzArm.param.json#L1325)to use a windowSize of 1 hour  [PT1H] instead of the default 15 minutes [PT15M].

This all seems to work just fine when redeployed, the alerts **windowSize** [or **aggregation granulatiry** as it's called in the portal condition] is correctly adjusted to 1 hour.
However when looking at the KQL query used in both the [documentation](https://azure.github.io/azure-monitor-baseline-alerts/services/Compute/virtualMachines/#os-disk-read-latency-ms) and the portal show up using the following:

![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/9294993/68ea0a61-c09a-46e9-8af6-9255d6964171)

where it seems that `avg(Val) by bin(TimeGenerated, 15m)` still only checks for the last 15 minutes.

We still get the alerts popping up for some servers, even though the average value over the period of an hour doesn't exceed the threshold for the machines.

Am I right at thinking the KQL query also needs to adjust based on the value provided for the windowSize, or can someone explain me how this works and why the values differ [and perhaps should]?

This issue seems to be the case for not just this specific alert, but also others, but this is a clear working example in our environment.

**Comment by Brunoga-MS** [comment]
Hello @powershellpr0mpt,
thanks for your question. WindowsSize and aggregation performed by the Summarize are different. There's no adjustment needed since the windowsSize is driving the time range of data to be considered (last 1h of data) whilst the summarize is aggregating data in that windows based on intervals (15m). This second aggregation is only meant to relax the customer from the alert fatigue and to have only one record to be checked. Too many records could either creates false positives or too many alerts.

Hope that helps.

Thanks,
Bruno.

**Comment by powershellpr0mpt** [comment]
Thanks for the explanation @Brunoga-MS , makes it a lot clearer for me and my colleagues.
Unfortunately there's not much explanation on this subject in MS docs either [as far as I was able to locate], so this was helpfull!

This can be closed now 👍🏻

**Comment by Brunoga-MS** [comment]
Thanks @powershellpr0mpt.
