### ISSUE TITLE
[Question/Feedback]: Hybrid VM Heartbeat alert automatically resolving

### ISSUE THREAD

**Issue by darioman1** [Azure/azure-monitor-baseline-alerts#267]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Hi
We have a issue where the Heartbeat alert for Hybrid VM's automatically changes to "resolved" state. Even though the VM is still down.
We turn of the VM, the Heartbeat alert fires. Then we leave the VM down, but the Heartbeat alert automatically resolves after 10-15minutes even thought the VM is still down.

Is this normal behavior or did we configure something wrong?

**Comment by Brunoga-MS** [comment]
Hello @darioman1 ,
thanks for your feedback. What you are experiencing is the normal behavior of the Auto Resolve setting. In the param file we set parameters like windows size (the data time range we look at) to the last 15 minutes and evaluation frequency (the query run interval) at 5 minutes. According to the Auto Resolve behavior, if no records are returned the alert is set to resolve. Since the query will query the last 15 mins, if no record is found the alert is considered resolved. Default parameter values should give enough time to verify the alert and remediate if necessary if we are talking about a production environment. However, if you have different requirement, to resolve the issue you can set the **_VMHeartBeatRGWindowSize_** param value in the param file to something bigger (i.e. PT12H or PT24H) to look at a wider data time range. This will ensure the alert does not get resolved before configured interval.

Thanks,
Bruno

**Comment by darioman1** [comment]
Hi
As you said, if no record is found, the alert will be considered resolved.
But this is the state of the Logs right after alert got resolved.
![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/161855045/1733e206-c1fa-4f9f-9a37-c3e354efb761)

I don't understand why the alert gets marked as resolved, even tough a aggregated value of 35 meets the alerts condition for "aggregatedValue">10.

As far as I know, Azure resolves the alert only if the condition isn't met anymore?`

Thank you in advance
BR
Dario

**Comment by Brunoga-MS** [comment]
Hello @darioman1 ,
is this still happening or did it happen only during a precise timeframe? I tried to repro it, but it was working correctly on my side. If you would like to investigate, you should run the query using the same settings as the alert, hence for the timerange you should select the last 15 mins (using the "**_| where timerange > ago(15m)_**" in your query)

**Comment by Brunoga-MS** [comment]
Hello @darioman1 ,
are there any news about this one? If not I would close this issue as resolved. Waiting for your input before closing it.

Thanks,
Bruno.

**Comment by Brunoga-MS** [comment]
Hello @darioman1 ,
I am going to close this issue since no news from you over the last 10 days.

Feel free to reopen, should it be the case.

Thanks,
Bruno.
