### ISSUE TITLE
[Question/Feedback]: policy trigger questions

### ISSUE THREAD

**Issue by jeromeecho** [Azure/azure-monitor-baseline-alerts#273]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

when i move a subscription to the alz which has AMBA attached, i noticed that only two action groups(action group and SH action group)  and two alert rule processing rules( apply action group and suppressed) are created, but all the service and resource health alerts are not created, since they are subscription level alerts, are they supposed to created automatically? but not by running remediation tasks? Could someone help clarify that? by the way, I am not change any para for alert effect in para file.

**Comment by Brunoga-MS** [comment]
Hello @jeromeecho ,
thanks for your question.
If my understanding is correct, you just moved a subscription under a new/different management group that has the AMBA-ALZ  pattern configured. This operation triggered the **_Not Compliant_** state and the relevant remediation because of the change (it is now under a different management group). This is not the case for subscription contained resources whose resourceId remained unchanged. In this case, there's no trigger for the policy compliance since no new resources or changes to the existing ones happened. In this situation, you need to run the remediation script as documented in the [Remediate Policies](https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/deploy/Remediate-Policies/) page.

Thanks,
Bruno.

**Comment by Brunoga-MS** [comment]
Hello @jeromeecho ,
are there any news about this one? If not I would close this issue as resolved. Waiting for your input before closing it.

Thanks,
Bruno.

**Comment by jeromeecho** [comment]
Hello @Brunoga-MS 
Thanks for the information. Please check my question which i tested in my lab. actions groups and alert processing rule are created automatically, i believe it is done by policy automatically.  I totally understand any resource related alert rule(metric rule..etc) will be created whenever the resource is created.   How about the service/resource health alert rule? since they are subscription level alert rule, they should be created automatically , right? Basically, I am asking if we deploy AMBA alz pattern,  whenever there is new subscription move to the hierarchy,  which rule or resources AMBA related will be created automatically? Based your answer, we need to run the remediation task manually to create all those things including "two action groups, alert  processing rule and service healthy alert". I hope that make a little bit clarification of my question. Thanks.

**Comment by Brunoga-MS** [comment]
Hi @jeromeecho ,
Based on your description they should be creating automatically like alert for any other resource in the moved subscription. At this point, I would check the output of the remediation tasks. This behavior sound very strange to me and I suspect some failure in the remediation task. Could you please share remediation task results and details in case of failures?

Thanks,
Bruno.

**Comment by jeromeecho** [comment]
Hi Brunoga,  i check the remediation task , it has some error but not enough for troubleshooting. I believe it is due to my visual studio subscription somehow, I tested it with another subscriptions, all service health alert rules are created automatically.  I think i am good for now, We can close the issue. Thank you so much for the help. Really appreciated it.
