### ISSUE TITLE
AMBA policy ALZ_ServiceHealth_ActionGroups Missing when remediating AMBA policies - Bug Report

### ISSUE THREAD

**Issue by Greg-Court** [Azure/azure-monitor-baseline-alerts#284]
When remediating AMBA policy assignments (brownfield environment), following steps outlined [here](https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/deploy/Remediate-Policies/) running the following commands:

```
.\patterns\alz\scripts\Start-AMBARemediation.ps1 -managementGroupName $managementManagementGroup -policyName Alerting-Management
.\patterns\alz\scripts\Start-AMBARemediation.ps1 -managementGroupName $connectivityManagementGroup -policyName Alerting-Connectivity
.\patterns\alz\scripts\Start-AMBARemediation.ps1 -managementGroupName $identityManagementGroup -policyName Alerting-Identity
.\patterns\alz\scripts\Start-AMBARemediation.ps1 -managementGroupName $LZManagementGroup -policyName Alerting-LandingZone
.\patterns\alz\scripts\Start-AMBARemediation.ps1 -managementGroupName $LZManagementGroup -policyName Alerting-HybridVM
.\patterns\alz\scripts\Start-AMBARemediation.ps1 -managementGroupName $pseudoRootManagementGroup -policyName Alerting-ServiceHealth
.\patterns\alz\scripts\Start-AMBARemediation.ps1 -managementGroupName $pseudoRootManagementGroup -policyName Notification-Assets
```

All remediation commands complete successfully, apart from `Start-AMBARemediation.ps1 -managementGroupName $pseudoRootManagementGroup -policyName Alerting-ServiceHealth`, producing the following error:

```
Exception: /azure-monitor-baseline-alerts/patterns/alz/scripts/Start-AMBARemediation.ps1:106
Line |
 106 |          throw "No policy assignments found for policy $policyName at  …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | No policy assignments found for policy ALZ_ServiceHealth_ActionGroups at management group scope *redacted*

```
![image](https://github.com/Azure/Enterprise-Scale/assets/83063651/c73cffdc-a746-4c8c-9742-63173f661489)

**Comment by arjenhuitema** [comment]
Hi @Greg-Court, 

In #278 you mentioned that you rolled out the latest version using Azure CLI, which got me revisiting this issue.

My initial reaction is not correct because it applies solely to deployments via the ALZ portal accelerator.

I've looked into the script and identified a problem relating to how the wait time was implemented. After initiating the remediations of ALZ_ServiceHealth_ActionGroups, a 5 minute delay is factored in because it is a prerequisite for the subsequent deployment of service health alerts. The code that was implemented to address the remediation of just the ALZ_ServiceHealth_ActionGroups prior to the wait time failed to accurately list the policy, resulting in this error.

The latest script update is in our development branch. The merge to the main branch is scheduled for completion by the end of August.

- [Start-AMBARemediation.ps1](https://github.com/Azure/azure-monitor-baseline-alerts/blob/dev-alz-pattern/patterns/alz/scripts/Start-AMBARemediation.ps1)
