### ISSUE TITLE
[Feature Request]: Enable Azure Monitor Baseline Alerts from standard VM metrics rather than VM Insights

### ISSUE THREAD

**Issue by Greg-Court** [Azure/azure-monitor-baseline-alerts#296]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

As in the title, would this be possible? For clients wanting to keep costs to a minimum, would it be possible to use the inbuilt VM Metrics rather than needing to enable VM Insights? And not just for VMs but for other resources too, that support it.

**Comment by Brunoga-MS** [comment]
Hello @Greg-Court ,
thanks for your question. Although it is possible to use VM metrics aka host metrics, guest metrics give a better perspective of how the operating system and the contained services, if monitored, are performing. Unfortunately, we know and we considered that guest metrics come with costs. Moreover, we also monitor the hybrid machines, so it was not possible to rely on host metrics since Hybrid VMs do not emit metrics.

Thanks,
Bruno.

**Comment by arjenhuitema** [comment]
Hello @Greg-Court, 

Thank you for your feedback. Regarding the ALZ pattern, there was an initial debate when establishing the policies. Ultimately, we decided on VM Insights because it offered a more holistic approach.

Metrics are great, and policy development is in progress. These policies are detailed in #298 and after additional development and testing, AMBA may provide more guidance on implementing Policy Sets that include VM Metric policies, potentially via the ALZ pattern or alternative patterns.

**Comment by Brunoga-MS** [comment]
Hello @Greg-Court ,
given Arjen's answer, can this issue be considered as addressed?

Thanks,
Bruno.

**Comment by Brunoga-MS** [comment]
Closing this issue as no further comments since last 2 weeks.
