### ISSUE TITLE
[Question/Feedback]: Cannot be used after import

### ISSUE THREAD

**Issue by 523120215** [Azure/azure-monitor-baseline-alerts#327]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Hi Team,
I had some problems using dashboard.

My Grafana version is : 11.2.0
The dashboard id is 21256.

When I successfully imported the dashboard, an error appeared in the upper right corner
“Templating
Failed to upgrade legacy queries”
I can get subscriptions, workspace_scop, workspace, Resouce scop as normal.
But I can't get some variables, such as amba_eventhub_UserErrors, when I click "Run query", the error "Templating" appears
Failed to upgrade legacy queries”. 

then , my panel cannot display normally
See the details as image:
<img width="1201" alt="image" src="https://github.com/user-attachments/assets/0e7db92e-15d3-47be-b665-c05b7e636b3a">

<img width="1204" alt="image" src="https://github.com/user-attachments/assets/5087bf4b-7b4c-4ce9-b602-d6ed8cd9023f">

Looking forward to your reply.

BR

**Comment by judyer28** [comment]
Hello @523120215, have you followed the instructions to configure the JSON API Grafana plugin as specified under the Installation and configurations instructions here:  https://grafana.com/grafana/dashboards/21256-azure-infrastructure-data-monitoring/?  This is needed in order to properly define the variables such as "amba_eventhub_UserErrors."

**Comment by 523120215** [comment]
Thank you very much.  I missed it.
