### ISSUE TITLE
[BUG] - Deploy VNetG ExpressRoute QOS Bit In/Out Alert remediation fails

### ISSUE THREAD

**Issue by birdnathan** [Azure/azure-monitor-baseline-alerts#356]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

The following ExpressRoute Metric alerts never come into compliance:
![image](https://github.com/user-attachments/assets/dd0105a5-11eb-4cfe-8245-57276235cd14)

Looking into it, it looks as though the issue is very much similar to what was fixed here for the ExpressRoute CPU Alerts:
https://github.com/Azure/azure-monitor-baseline-alerts/issues/278

**Comment by birdnathan** [comment]
@RoshE03 - FYI

**Comment by arjenhuitema** [comment]
@birdnathan Thank you for reporting this issue. I will look into it.

**Comment by arjenhuitema** [comment]
@birdnathan, I identified the problem. Although the alerts were generated correctly, the policy never reached a compliant state. This occurred because the values in the Existence Condition didn't match the actual alert values.

The current issue will close upon the merging of the PR. Following that, proceed to the subsequent steps:

**Next steps**
1. If you're on the latest release, this change is non-breaking, so you can update the policies by deploying AMBA-ALZ over your existing setup. 
2. If you are using an earlier version, please consult this guide: https://aka.ms/amba/alz/update
3. Given that existing alert rules have different values, you will need to perform a policy remediation using our script or manually through the portal. See [Remediate Policies](https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/deploy/Remediate-Policies/) for more information.

Please feel free to reach out if you have any further questions.
