### ISSUE TITLE
[Question/Feedback]: What is the best way to send alerts to an ARM role if PIM is being used

### ISSUE THREAD

**Issue by kasimrehman** [Azure/azure-monitor-baseline-alerts#359]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Large-scale deployment of alerts policies necessitates a mechanism to send alerts to not statically defined alert receivers but based on the role they have for each enabled subscription. This seems to work fine if receivers have, say, the owner role in a subscription. If alert policies are deployed at a management group node, with a single assignment, all attached subscriptions will have their alerts enabled such that they reach the owner of each subscription. However, this does not seem to work if the organisation has enabled PIm and hence there is no one defined as "Owner" most of the time. What is the recommended way assign the alert policies in such a scenario?

**Comment by Brunoga-MS** [comment]
Hello @kasimrehman ,
thanks for your feedback and sorry if it took a bit to respond. We did some investigation in the meantime and we found out that PIM roles do not work. When using a PIM role, the role assignment if driven by a different resource type and so not included in the classic notification. Unfortunately this is not something we can resolve in AMBA since it is not something the AMBA team has control on. The notification feature is at an higher level and AMBA just uses it. Given that, I recommend you to open a support ticket (not mentioning AMBA) including this issue link in the details so we can cross reference it internally if needed.

I am going to close this issue, since no action for this team.

Thanks,
Bruno.
