### ISSUE TITLE
'where' operator: Failed to resolve table or column expression named 'Heartbeat'. A semantic error occurred.. The request had some invalid properties

### ISSUE THREAD

**Issue by ThojoUno** [Azure/azure-monitor-baseline-alerts#414]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

Trying to deploy AMBA into brownfield environment. No VM based schedule query rule alerts are being created, all give similar error as in the title.

**Comment by ThojoUno** [comment]
I've found 2 root causes for this issue. 
1) Enable Azure Monitor for VMs policy had not run, so the virtual machines were not collecting monitoring data, and tables did not exist in Log Analytics.
2) Access control on the Logging resource group is coming from the managed identities defined at the <intermediate root>-Platform level and these differ from the managed identities created at the <intermediate root>-landingzones level. Therefore, virtual machines created underneath the landingzone management group structure do not have permissions to update/read DCRs and log analytics in the Logging resource group (platform-management)

**Comment by tagolovina** [comment]
Hi @ThojoUno,
For the virtual machine log alerts the VM insights needs to be enabled on the VMs that are targeted. It is prerequisites, as VM initiative, as well as the Hybrid VM initiative, requires VM Insights to be in place before running the remediation. The remediation will fail if VM Insights is not configured because the necessary table (InsightsMetrics) will not be found when creating the alert.

Make sure to apply the configuration for VM Insights using the approach you prefer the most (policy, manual configuration, ARM template, portal, etc.). You can read more about VM Insights at:

[Log Alerts](https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/Monitoring-and-Alerting/#log-alerts)
[Enable VM Insights](https://learn.microsoft.com/en-us/azure/azure-monitor/vm/vminsights-enable?tabs=portal)
[Enable VM insights using Azure Policy](https://learn.microsoft.com/en-us/azure/azure-monitor/vm/vminsights-enable-policy)
[[Enable VM insights using Resource Manager templates](https://learn.microsoft.com/en-us/azure/azure-monitor/vm/vminsights-enable-resource-manager)](https://learn.microsoft.com/en-us/azure/azure-monitor/vm/vminsights-enable?tabs=portal#enable-vm-insights-using-arm-templates)

**Comment by ThojoUno** [comment]
That did solve cause 1, but cause 2 is the managed identities created for landingzones mg don't get applied to the management mg so dcrs don't get enabled

**Comment by tagolovina** [comment]
Hi @ThojoUno , 
If you used your own managed identity, before executing the deployment, ensure that the existing UAMI is assigned the Monitoring Reader role at the **pseudo root Management Group**.  https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/Available_features/Bring-your-own-Managed-Identity/

When a new UAMI is created by the deployment template, the Monitoring Reader role is is automatically assigned at the pseudo root Management Group level(which includes both Platform and Landing Zones MGs) during the deployment.

**Comment by Brunoga-MS** [comment]
hello @ThojoUno ,
we haven't heard anything back from you. Assuming that your issue has been addressed using the provided info, I am going to close this one as resolved.

Feel free to reopen it or to create a new one should it be the case.

Thanks,
Bruno.
