### ISSUE TITLE
[Question/Feedback]: Unable to deploy via pipeline using ubuntu-latest

### ISSUE THREAD

**Issue by ac-matthews** [Azure/azure-monitor-baseline-alerts#64]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Hi,

I'm having an issue deploying AMBA as part of our ADO pipeline. When using image version 'Ubuntu-Latest' , I get a script failed message saying the parameter file was unable to be parsed. However when using 'Windows-Latest' the deployment works just fine. There are no errors with the param file and the pipeline stage is basically identical to the example provided in the repo. Any advice on this would be greatly appreciated, cheers! 

![Screenshot 2023-11-02 142413](https://github.com/Azure/azure-monitor-baseline-alerts/assets/113511795/981c6fe7-00d4-457b-aab3-f4d5061c7af4)

**Comment by philrice** [comment]
@ac-matthews - I had this issue and for me I could resolve it by changing the the az deployment line in the pipeline yaml , so that the --parameters was using the full URI to the params file in github (in the same way the template URI does). 
The default pipeline yaml had a relative path for the parameters file  in windows format :

` inlineScript: |
        az deployment mg create --template-uri https://raw.githubusercontent.com/Azure/azure-monitor-baseline-alerts/main/patterns/alz/alzArm.json --location $(location) --management-group-id $(ManagementGroupPrefix) --parameters .\patterns\alz\alzArm.param.json`

You could also try switch the backslashes  for forward slashes, as that will likely fix it for Ubuntu (but break for Windows)

**Comment by paulgrimley** [comment]
Apologies for the delay in response , we had discussed this earlier in the week and given you had a workaround we reduced the priority as we are driving a few enhancements to AMBA, adding @arjenhuitema to comment but also thanks @philrice for your input also!

**Comment by ac-matthews** [comment]
Many thanks @philrice the forward slashes worked :) will be sticking to ubuntu for our pipelines so that will sort it for now!

Also no problem @paulgrimley, will keep and eye out for any other fixes relating to this issue
