### ISSUE TITLE
[Question/Feedback]: Automatically delete alert rules

### ISSUE THREAD

**Issue by PepsiCocaCola** [Azure/azure-monitor-baseline-alerts#82]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Description

Hello,
I have tried this project out and it seems to be working well. However when I delete a resource, the alert rules stays. This should be working as intended, because the policy only deploys alert rules and nothing else. I want to be able to delete corresponding alert rules automatically when deleting a resource. What's the best way to approach this?

**Comment by paulgrimley** [comment]
Pinged @mbrat2005 for comment

**Comment by mbrat2005** [comment]
Hi @PepsiCocaCola, sorry for the delay. In order to automate the cleanup of alerts, you'll need to run some code on a schedule or by trigger and with an identity which has permissions to delete the alert resources at whichever scopes they'll exist. As noted, Azure Policy doesn't include functionality to remove resources it deploys. 

The script at https://github.com/Azure/azure-monitor-baseline-alerts/blob/main/patterns/alz/scripts/Start-AMBACleanup.ps1 could be a good starting place for code but paring down to just alert resources and modifying the resource graph queries to alerts where target resources do not exist. 

Once the code is together, I would run it in a consumption-tier Function. Grant the Function's managed identity just the permission to delete the required alert resources at the org Management Group scope with a custom role and run on something like a 24 hour schedule. In an ALZ implementation, placing this in your Management platform subscription would make sense.
